version: '2'
services:
  mosquitto:
    image: eclipse-mosquitto
    ports:
     - 1883:1883
  plm_connector:
    build: plm_connector
    links:
     - mosquitto
    volumes:
     - ./plm_connector/config:/config
    command: ["-c", "/config/config.json", "-v"]
  pyro-ns:
    image: farshidtz/pyro4-ns
    ports:
     - "9090-9091:9090-9091"
    command: ["--host=pyro-ns", "--nathost=localhost", "--natport=9090"]
  python-agent:
    build: training/
    depends_on:
     - pyro-ns
    volumes:
     - ./training/model:/model
     - ./training/agent:/agent
    ports:
     - "9101-9106:9101-9106"
    #command: ["--bname=Agent", "--bpath=/agent/agent.py", "--host=python-agent", "--port=9100", "--ns", "--nathost=localhost", "--natport=9100"]
    command: ["6"]
