version: '2'
services:
  pyro-ns:
    image: farshidtz/pyro4-ns
    ports:
      - "9090:9090"
    command: ["--host=pyro-ns"]
  python-agent:
    build: training/
    depends_on:
      - pyro-ns
    volumes:
      - ./training/model:/model
      - ./training/agent:/agent
    ports:
      - "9100:9100"
    command: ["--bname=Agent", "--bpath=/agent/agent.py", "--host=python-agent", "--port=9100", "--ns"]
  ceml:
    build: data-processing-agent/
    depends_on:
      - pyro-ns
      - python-agent
    volumes:
      - ./data-processing-agent/config:/config
    ports:
      - "8319:8319"
  # python-test:
    # build: 
      # context: training/
      # dockerfile: Dockerfile-test
    # depends_on:
      # - pyro-ns
      # - python-agent
