version: '2'
services:
  pyro-ns:
    image: farshidtz/pyro4-ns
    ports:
      - "9090:9090"
    command: ["--host=pyro-ns"]
    stop_signal: SIGKILL
  python-agent:
    build: training/
    depends_on:
      - pyro-ns
    volumes:
      - ./data:/data
    ports:
      - "9100:9100"
    command: ["--bname=Agent", "--bpath=agent/agent.py", "--host=python-agent", "--port=9100", "--ns"]
    stop_signal: SIGKILL
  ceml:
    build: ../data-processing-agent/
    volumes:
      - ../data-processing-agent/config:/config
    links:
      - pyro-ns
      - python-agent
    ports:
      - "8319:8319"
    command: ["/config/conf.cfg"]
    stop_signal: SIGKILL