version: '2'
services:
  pyro-ns:
    image: farshidtz/pyro4-ns
    ports:
      - "9090:9090"
    command: ["--host=pyro-ns"]
  python-agent:
    build: .
    depends_on:
      - pyro-ns
    ports:
      - "9100:9100"
    command: ["--bname=Agent", "--bpath=agent/agent.py", "--host=python-agent", "--port=9100", "--ns"]
  # python-test:
    # build: 
      # context: .
      # dockerfile: Dockerfile-test
    # depends_on:
      # - pyro-ns
      # - python-agent
  ceml:
    build: ../data-processing-agent/
    links:
      - pyro-ns
      - python-agent
    ports:
      - "8319:8319"